### ISSUE TITLE
User is put on call when 'getting' a user

### ISSUE THREAD

**Issue by johntdyer** [stripe-contrib/pagerbot#23]
When I `get` someone it appears to put that person on duty for 5 minutes. Here is what I did:

```
[11:17 AM]  John Dyer: pagerbot: get jake because we need to test something
[11:17 AM]  pagerbot BOT: Contacted Jake Herbst, see the incident created here.
```

and at the time I was on duty and Jake was paged but it also put him on duty for five minutes.  Is this expected? 

-John

**Comment by macobo** [comment]
It is - so pagerduty doesn't actually support paging someone using their API. The `get person` flow is a hack that involves putting a person on call for a while and then triggering an escalation for that schedule. Another downside is that the person will get notified that they went on-call.

I suggest setting up a fake schedule and escalation policy for this - this way the 5-minute override doesn't actually capture any pages.

Lmk if this makes sense!

**Comment by johntdyer** [comment]
Thanks
