### ISSUE TITLE
pagerbot and private groups inside of slack

### ISSUE THREAD

**Issue by awesinine** [stripe-contrib/pagerbot#24]
Loving Pagerbot!  It seems as if it doesn't work in private groups within slack.  Is this by design or did I miss something on the config side?

**Comment by macobo** [comment]
Sadly this is a design limitation; Pagerbot uses [outgoing webhooks](https://api.slack.com/outgoing-webhooks) to get data from slack, but as the docs say:

> The outgoing webhook integration is only available in public channels. If you would like to get data out of private groups and DMs in real-time, try a slash command.

Hopefully this isn't a deal-breaker; let me know if there's anything I can do to help!

**Comment by amalakar** [comment]
I think [slash-command](https://api.slack.com/slash-commands) do not have this limitation, and supports making http post call (similar to outgoing webhooks I believe). That may help us get rid of this limitation.

**Comment by macobo** [comment]
The latest master has Slack Real Time Messaging support which should support this use-case.

Please test and let us know how it works! :)
