### ISSUE TITLE
Default bot settings don't seem to be being applied - Angular error when trying to set channels

### ISSUE THREAD

**Issue by shedd** [stripe-contrib/pagerbot#27]
By default after standing up the app on Heroku, I don't seem to be able to add a channel for the Slack config.

/bot doesn't seem to be returning the `bot_defaults`

Instead, it only seems to return `{}` at the outset, and then once saved, name and adapter: `{"name":"","adapter":"slack"}`

This leads to the following Angular error when trying to add a channel:

```
TypeError: Cannot read property 'push' of undefined
    at k.$scope.add_channel (bot-setup.js:29)
    at angular.js:10821
    at angular.js:19062
    at k.$eval (angular.js:12658)
    at k.$apply (angular.js:12756)
    at HTMLAnchorElement.<anonymous> (angular.js:19061)
    at HTMLAnchorElement.n.event.dispatch (jquery-1.11.0.min.js:3)
    at HTMLAnchorElement.r.handle (jquery-1.11.0.min.js:3)
```

Screenshot: http://cl.ly/image/0B0t0n3f1j2d

I worked around this by using Curl to post the proper bot-defaults to the /bot endpoint:

```
curl -X POST -d "{\"name\":\"pagerbot\",\"channels\":[\"general\"],\"adapter\":\"slack\",\"irc\":{\"server\":\"irc.freenode.org\",\"port\":6697,\"use_ssl\":false},\"slack\":{\"emoji\":\":frog:\"},\"hipchat\":{}}" "http://app.url/bot" -H "Content-Type: application/json"
```

I was able to reproduce this issue by tearing down my MongoDB instance and setting it up again - same issue happened.

**Comment by macobo** [comment]
Sorry for not responding to this in ages - is this still reproducible?
