### ISSUE TITLE
Call on-call duty

### ISSUE THREAD

**Issue by vudinhnghi89** [stripe-contrib/pagerbot#29]
Hi Awesome,
I'm using your application and I really like it. Just one more thing to make it perfect to me is create a incident on pagerduty, I don't see it on your manual page.
Do you have plan to do that ? 

I really appreciate your efforts
Looking forward to hearing from you

**Comment by dbenamy** [comment]
You probably want the get_person plugin. Then you can `@pagerbot get vudinhnghi89 the site's down`.

**Comment by macobo** [comment]
Thanks to @dbenamy you are able to call schedules as well now on the latest master.

`pagerbot: get schedulename yourreason`
