### ISSUE TITLE
How do you set to 'deployed' without Heroku?..

### ISSUE THREAD

**Issue by gadg3ts** [stripe-contrib/pagerbot#30]
I'm trying this out for our slack/pagerduty integration project.
I've managed to get it to listen on 0.0.0.0 but it doesn't appear to be taking in data from slack (although I am seeing requests from AWS, which would be where slack is hosted):
The below shows be attempting to set it as an environment variable.
 $ su pagerbot -c 'export DEPLOYED=true; cd /home/pagerbot; bundle exec ruby lib/pagerbot.rb admin slack'  
INFO lib/pagerbot.rb:97:in `<main>': Is_admin is true
== Sinatra (v1.4.6) has taken the stage on 4567 for development with backup from Thin
Thin web server (v1.6.3 codename Protein Powder)
Maximum connections set to 1024
Listening on 0.0.0.0:4567, CTRL+C to stop

I also tried adding the file 'config' mentioned in pagerbot.rb, but my exposure to ruby is pretty much limited to using puppet...
Thanks,

**Comment by macobo** [comment]
Hi,

Thanks for checking out the project.

Are you trying to start the admin page (to configure pagerbot) or the bot itself?

For administration web interface, an adapted version of what you need to run is the following (make sure DEPLOYED flag is unset):
```
bundle exec ruby lib/pagerbot.rb admin slack
```

For running the bot (once it's configured):
```
export DEPLOYED=true
bundle exec ruby lib/pagerbot.rb web slack
```

Let me know if this helps.

**Comment by gadg3ts** [comment]
I'm trying to start the bot itself.
I've got it talking to pagerduty fine, however slack is being a bit more
problematic.
I saw the messages about it not being able to talk to private channels,
so I'm trying a different one.

The command you gave for running the bot does work, however that then
defaults to listening only on localhost - there's a pull request from
someone else that has the app binding to 0.0.0.0 - so in 'web' mode,
it's not then listening for traffic form outside is it.
Is it easy enough to get it to listen to the outside world?  (and if so,
how can I do that?)

Thanks,
Sean

**Comment by macobo** [comment]
The bot does bind to 0.0.0.0 by default (for some reason the init message for sinatra lies).

Keep in mind th but the default port is set to 4567, you need to take into account when configuring the webhooks or use a custom port for the web server.
