### ISSUE TITLE
[Slack] Pagerbot doesn't respond to comments made to @pagerbot

### ISSUE THREAD

**Issue by astorije** [stripe-contrib/pagerbot#31]
On Slack, the bot doesn't answer any command made to the `@` version, even though #9 tells me it's supposed to:

> **astorije**
> @pagerbot put me on oncall for next 30 minutes
> **astorije**
> pagerbot put me on oncall for next 30 minutes
> **pagerbot**
> Ok. Put ... on ... from 1:08 PM May 4 (-0400) until 1:38 PM May 4 (-0400).

**Comment by macobo** [comment]
When setting up the webhook, make sure to include `@pagerbot` as one of the triggers.
