### ISSUE TITLE
Not pulling down users or schedules

### ISSUE THREAD

**Issue by matwithonet1** [stripe-contrib/pagerbot#38]
When I added my full access v2 pagerduty key, the admin console said that it was connected to pagerduty but when I start up pagerbot, it never gets any users or schedules. I have tried many ideas to figure this out but I am stuck. Any help would be greatly appreciated!

For a little more context, this is in the logs when I deploy the app:

:users=>[], :schedules=>[]

When I run the curl command from the PagerDuty api, I get a list of all users and schedules, so I know the key is working. Also, after throwing some debugging messages in, I am seeing expected payloads coming back from PagerDuty.

Update: While trying to figure this out, I remembered that my admin console was acting kind of wonky. The user and schedule alias sections won't open. I get a 500 back when I try to click on them. 

I just found that the Total attribute, in the payload coming back from PagerDuty, is null.

**Comment by matwithonet1** [comment]
For a little more context, this is in the logs when I deploy the app:

:users=>[], :schedules=>[]

When I run the curl command from the PagerDuty api, I get a list of all users and schedules, so I know the key is working.

**Comment by samoht625** [comment]
@matwithonet1 - I ran into the same problem. This can be fixed by using v1 Pagerduty API keys instead of v2.

**Comment by matwithonet1** [comment]
Alrighty. I modified PagerBot to use v2 if you would like me to push it back up, I could.

**Comment by samoht625** [comment]
Hey, I'm not the maintainer of this project so hard for me to say. If you
think the change is pretty clean and self-contained, could be worth pushing
back upstream!

**Comment by macobo** [comment]
@matwithonet1, good to hear you figured out a way around this! Please try opening a PR, ideally we'd figure out a solution that would work for both versions of the API.

**Comment by ojung** [comment]
I have the same issue. At first tried to use a v2 key, then I read @samoht625's tip and changed it to a v1 key. Still no `users` or `schedules` collection in mongo.
I restarted the application and wiped mongo to reconfigure it with a v2 key from the beginning.
@matwithonet1 Can you share your updated version?

**Comment by amalakar** [comment]
https://github.com/stripe-contrib/pagerbot/pull/45 fixes v2 style api response parsing.

**Comment by xaviershay** [comment]
Note that V1 API keys now fail silently. They appear to work initially, but don't paginate properly so leave you with partial data.

**Comment by macobo** [comment]
This is now fully fixed on the latest master.

Problem was indeed the mixing of v1 and v2 API keys, but current state should work with both thanks to the folks at Pagerduty implementing [a versioned accept header](https://v2.developer.pagerduty.com/docs/migrating-to-api-v2#versioned-accept-header)

I'd suggest updating your keys though, pagerduty will start decommissioning v1 in july, meaning the old keys might not work anymore.
