### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by ajmonger** [stripe-contrib/pagerbot#55]
Whenever I try the "list" or "people" commands in slack, the bot says "Hmm, that didn't seem to work: No such file or directory @ rb_sysopen - /app/templates/list_irc.erb".  I can see the Users and Schedules in the Pagerbot setup under the "User Aliases" and "Schedule Aliases" tabs though

**Comment by ajmonger** [comment]
I'm using the pagerduty API v2 key

**Comment by macobo** [comment]
Thanks for the report, this is fixed in the latest commit. Let me know if there are any additional problems!
