### ISSUE TITLE
Allow paging teams (escalation policies) as well as users

### ISSUE THREAD

**Issue by dshack** [stripe-contrib/pagerbot#6]
A common use case for other chatbots (as well as manually triggering incidents from the PD app or API) is to page the on-call for a given team.

It would be great if this tool could do that as well, probably by creating a page-<teamname> service for each EP in the account. As a bonus, since every service is owned by a single escalation policy, you would not have to use the temporary-override workaround.  

A nice-to-have would be the ability to alias escalation policy names as well.

**Comment by dbenamy** [comment]
If by some chance it's still useful, you can page a schedule with https://github.com/stripe-contrib/pagerbot/pull/43.

**Comment by macobo** [comment]
This is now merged, thanks!

**Comment by pratik60** [comment]
@macobo @dbenamy The above request was to page an escalation policy and not page a schedule. We should reopen this issue/feature-request
